# Generated by Django 4.0.6 on 2025-01-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alojamiento', models.CharField(max_length=50)),
                ('numero_personas', models.CharField(max_length=2)),
                ('Estado', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=300)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.campista')),
            ],
        ),
    ]
