# Generated by Django 4.0.6 on 2025-01-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campista',
            name='identificacion',
            field=models.CharField(default=1754488144, max_length=10),
            preserve_default=False,
        ),
    ]
